version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todolist_local_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
      - "5678:5678"
    command: [
        # copy from compose/local/django/start
        "bash",
        "-c",
        "set -o errexit && \
        set -eo pipefail && \
        set -o nounset && \
        python manage.py migrate && \
        pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8000",
      ]

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: todolist_local_postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  react:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    image: todolist_local_react
    container_name: react
    depends_on:
      - django
    ports:
      - "3030:80"

  # docs:
  #   image: todolist_local_docs
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./todolist:/app/todolist:z
  #   ports:
  #     - "7000:7000"
  #   command: /start-docs
